server:
  port: 9000

#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/small?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#redis
# Redis数据库索引（默认为0）
  redis:
    database: 0
  # Redis服务器地址
    host: wdx.kleme.top
  # Redis服务器连接端口
    port: 6379
  # Redis服务器连接密码（默认为空）
    password:
    #连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        pool.min-idle: 0
        # 连接超时时间（毫秒）
        timeout: 0
   

# mybatisplus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #表前缀
    table-prefix: sf_
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.smallflyingleg.sso.pojo




#CAS
cas:
  server:
    #CAS服务地址
    host.url: http://localhost:8080/cas
    #CAS服务登录地址
    host.login_url: http://localhost:8080/cas/login
    #CAS服务登出地址
    host.logout_url: http://localhost:8080/cas/logout?service=http://localhost:8080/cas

app:
  server:
  #应用访问地址
    host.url: http://localhost:9000
  #应用登录地址
  login:
    url: /cas/index
  #应用登出地址
  logout:
    url: /logout


constants:
  # QQ
  qqAppId: 101698287
  qqAppSecret: 3264980ccc09236770181afcf37be62f
  qqRedirectUrl: http://localhost:9000/QQLogin
  #WECAT
#  weCatAppId: xxxxxxxxxx
#  weCatAppSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
#  weCatRedirectUrl: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
